
export class HtmlHelperFactory {

    static get attributes() {
        return {
            action: "action",
            fontstyle: 'font-style',
            align: "align",
            alt: "alt",
            bgColor: "bgColor",
            background: 'background',
            backgroundcolor:'background-color',
            border: "border",
            checked: "checked",
            class: "class",
            color: "color",
            cols: "cols",
            colspan: "colspan",
            height: "height",
            hidden: "hidden",
            high: "high",
            href: "href",
            id: "id",
            label: "label",
            disabled: "disabled",
            bordercolor:'border-color',
            ariaSort: "aria-sort",
            ariadisabled: "aria-disabled",
            ariaInvalid: "aria-invalid",
            ariaChecked: "aria-checked",
            ariaRowindex: "aria-rowindex",
            ariaColindex: "aria-colindex",
            ariaselected: 'aria-selected',
            arialabel: "aria-label",
            ariaHidden: "aria-hidden",
            max: "max",
            maxLength: "maxLength",
            minLength: "minLength",
            maxlength: 'maxlength',
            multiline: "aria-multiline",
            min: "min",
            name: "name",
            placeholder: "placeholder",
            preload: "preload",
            radioGroup: "radioGroup",
            readonly: "readonly",
            rowSpan: "rowSpan",
            selected: "selected",
            size: "size",
            sizes: "sizes",
            spellCheck: "spellCheck",
            src: "src",
            style: "style",
            title: "title",
            originaltitle: 'data-original-title',
            type: "type",
            value: "value",
            width: "width",
            wrap: "wrap",
            textAlign: "text-align",
            lineheight: "line-height",
        }
    }

}